# Generated by Django 4.1.13 on 2024-10-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janajodapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
