# Generated by Django 4.1.13 on 2024-10-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janajodapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
