# Generated by Django 4.1.13 on 2024-10-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janajodapp', '0013_usereventrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereventrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
