# Generated by Django 4.1.13 on 2024-10-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janajodapp', '0017_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='location',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
