# Generated by Django 4.1.13 on 2024-10-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janajodapp', '0019_job_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='user',
        ),
    ]
