# Generated by Django 4.1.13 on 2024-10-22 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janajodapp', '0021_userreqjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreqjob',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userreqjob',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 22, 6, 39, 51, 397905, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
