# Generated by Django 4.1.13 on 2024-10-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janajodapp', '0021_jobapplication_user'),
        ('janajodapp', '0022_userreqjob_is_approved_userreqjob_posted_on'),
    ]

    operations = [
    ]
