# Generated by Django 4.1.13 on 2024-10-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janajodapp', '0024_alter_jobapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
