# Generated by Django 4.1.13 on 2024-10-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janajodapp', '0025_job_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_approved',
        ),
    ]
