# Generated by Django 4.1.13 on 2024-10-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janajodapp', '0028_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
    ]
