# Generated by Django 4.1.13 on 2024-10-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janajodapp', '0032_survey_surveyoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyoption',
            name='survey',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyOption',
        ),
    ]
