# Generated by Django 4.1.13 on 2024-11-13 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('janajodapp', '0041_remove_jobapplication_user_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='user_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_applications', to='janajodapp.userreqjob'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='janajodapp.job'),
        ),
    ]
