# Generated by Django 4.1.13 on 2025-01-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janajodapp', '0043_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('on_progress', 'On Progress'), ('done', 'Done')], default='received', max_length=20),
        ),
    ]
